In [30]:
from numpy import *
import operator
from os import listdir

In [31]:
def createDataSet():
    group = array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    labels = ['A','A','B','B']
    return group, labels

In [62]:
def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    diffMat = tile(inX, (dataSetSize,1)) - dataSet
    sqDiffMat = diffMat**2
    print('sqDiffMat', sqDiffMat)
    sqDistances = sqDiffMat.sum(axis=1)
    distances = sqDistances**0.5
    sortedDistIndicies = distances.argsort()   
    print('sortedDistIndicies', sortedDistIndicies)
    classCount={}          
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        print('voteIlabel', voteIlabel)
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
        print('classCount', classCount)
    sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True)
    print('operator.itemgetter(1)', operator.itemgetter(1))
    print('sortedClassCount', sortedClassCount)
    return sortedClassCount[0][0]

In [63]:
group, labels = createDataSet()

In [64]:
classify0([1, 5], group, labels, 3)

sqDiffMat [[ 0.   15.21]
 [ 0.   16.  ]
 [ 1.   25.  ]
 [ 1.   24.01]]
sortedDistIndicies [0 1 3 2]
voteIlabel A
classCount {'A': 1}
voteIlabel A
classCount {'A': 2}
voteIlabel B
classCount {'A': 2, 'B': 1}
operator.itemgetter(1) operator.itemgetter(1)
sortedClassCount [('A', 2), ('B', 1)]


'A'

In [8]:
import numpy as np

# np.tile( )

In [4]:
np.tile([0, 0], 5)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.tile([0,0], [1, 2])

array([[0, 0, 0, 0]])

In [7]:
np.tile([0,0], [2, 1])

array([[0, 0],
       [0, 0]])

# np.argsort( )

In [10]:
x = np.array([1, 4, -1, 99, 1, 2])
x.argsort()

array([2, 0, 4, 5, 1, 3], dtype=int64)

In [14]:
x = np.array([
    [0, 3],
    [2, 4]
])

In [15]:
# sort by column
x.argsort(axis=0)

array([[0, 0],
       [1, 1]], dtype=int64)

In [16]:
# sort by row
x.argsort(axis=1)

array([[0, 1],
       [0, 1]], dtype=int64)

# dict.get(key, default=None)

In [17]:
dict = {'Name':'Zara', 'Age':27}

In [18]:
dict.get('Age')

27

In [19]:
dict.get('Tyrion', "Winter is coming")

'Winter is coming'

# python.sorted( )

In [21]:
a = [5,7,6,3,4,1,2]
b = sorted(a)        # Keey orignal Array
print('a', a)
print('b', b)

a [5, 7, 6, 3, 4, 1, 2]
b [1, 2, 3, 4, 5, 6, 7]


In [25]:
L = [('b',2),('a',1),('c',3),('d',4)]
sorted(L, key=lambda x:x[1]) 

[('a', 1), ('b', 2), ('c', 3), ('d', 4)]

In [27]:
students = [('john', 'A', 15), ('jane', 'B', 12), ('dave', 'B', 10)]
sorted(students, key=lambda s: s[2])     # Sort by age

[('dave', 'B', 10), ('jane', 'B', 12), ('john', 'A', 15)]

In [28]:
dict = {'Name':'Zara', 'Age':27}

In [29]:
dict.items()

dict_items([('Name', 'Zara'), ('Age', 27)])

# operator.itemgetter()

In [65]:
a = [1, 2, 3]
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [68]:
get_pos_1 = operator.itemgetter(1)
print('get_pos_1(a)  ', get_pos_1(a))
print('get_pos_1(b)  ', get_pos_1(b))

get_pos_1(a)   2
get_pos_1(b)   [4, 5, 6]


In [69]:
get_pos_21 = operator.itemgetter(2, 1)
print('get_pos_21(a)  ', get_pos_21(a))
print('get_pos_21(b)  ', get_pos_21(b))

get_pos_21(a)   (3, 2)
get_pos_21(b)   ([7, 8, 9], [4, 5, 6])


In [70]:
# 取出第二维度的数据
b_21 = []
for temp in b:
    temp = get_pos_21(temp)
    b_21.append(temp)
b_21

[(3, 2), (6, 5), (9, 8)]

In [72]:
b_21 = [get_pos_21(temp) for temp in b]
b_21

[(3, 2), (6, 5), (9, 8)]