In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(1)

In [3]:
a.graph is tf.get_default_graph()

True

+ tf.get_variable() & tf.Variable()
+ tf.Graph()
+ tf.variable_scope()

In [4]:
g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable("Var", shape=(1,2,3), initializer=tf.zeros_initializer())

In [5]:
g2 = tf.Graph()
with g2.as_default():
    v = tf.get_variable("Var", shape=(2,3,2), initializer=tf.ones_initializer())

In [6]:
with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("Var")))    

[[[0. 0. 0.]
  [0. 0. 0.]]]


In [7]:
with tf.Session(graph=g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("Var")))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [8]:
g = tf.Graph()
with g.as_default():
    zero = tf.Variable(initial_value=tf.zeros(shape=[1]), name='Var')
    one = tf.Variable(initial_value=tf.ones(shape=[1,2,3]), name='Var1')
    
with tf.Session(graph=g) as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(zero))
    print(sess.run(one))

[0.]
[[[1. 1. 1.]
  [1. 1. 1.]]]


In [9]:
a = tf.constant([[1,2,3],[1,2,3],[1,2,3],[1,2,3]], name='a')
b = tf.constant([[3,4,5],[3,4,5],[3,4,5],[3,4,5]], name='b')

result = tf.add(a,b, name='add')
print(result)

Tensor("add:0", shape=(4, 3), dtype=int32)


In [10]:
result.get_shape()

TensorShape([Dimension(4), Dimension(3)])

+ tf.Tensor.eval() / sess.run(t)

In [11]:
t = tf.constant([1,2,3], name="test")

In [12]:
sess = tf.Session()
with sess.as_default():
    print(t.eval())
    print(sess.run(t))

[1 2 3]
[1 2 3]


In [13]:
sess = tf.Session()
print(t.eval(session=sess))

[1 2 3]


In [14]:
test = tf.constant([1,2,3], name='test')

In [15]:
sess = tf.Session()
with sess.as_default():
    print(sess is tf.get_default_session())
    
    print(test.eval() == sess.run(test))
    print(test.eval())
    print(sess.run(test))

True
[ True  True  True]
[1 2 3]
[1 2 3]


**`sess.run() 可以一步获取多个tensor中的值`**

In [16]:
a = tf.constant([1, 2, 3], name='a')
b = tf.constant([3, 4, 5], name='b')

In [17]:
add = tf.add(a, b, name='add')
mul = tf.multiply(a, b, name='mul')

In [18]:
with tf.Session() as sess:
    print(sess.run([add, mul]))
    print(add.eval(session=sess), mul.eval(session=sess))

[array([4, 6, 8], dtype=int32), array([ 3,  8, 15], dtype=int32)]
[4 6 8] [ 3  8 15]
