In [1]:
import tensorflow as tf

In [ ]:
tf.expand_dim(Tensor, dim)

labels = [1,2,3]
x = tf.expand_dim(labels, 0)
x = tf.expand_dim(labels, 1)

In [ ]:
矩阵拼接

In [ ]:
tf.pack
将一个 R-dim 张量列表，沿着 axis 轴组合成一个 R+1 维的张量
x = [1,2]
y = [3,4]
z = [5,6]
tf.pack([x,y,z])
tf.pack([x,y,z], axis=1)

In [ ]:
tf.concat()
将张量沿着指定纬度拼接起来

In [ ]:
tf.concat()

In [26]:
sess = tf.InteractiveSession()

t1 = [[1,2,3], [4,5,6]]
t2 = [[7,8,9], [10,11,12]]

con1 = tf.concat([t1,t2], 0)
print(sess.run(con1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
sess = tf.InteractiveSession()

a = [[1,2], [3,4], [5,6]]
x = tf.random_shuffle(a)

print(sess.run(x))

In [ ]:
tf.argmax() / tf.argmin
找到给定 Tensor 中在指定轴 axis 上的最大值 / 最小值 的位置

In [43]:
Rand = tf.random_uniform([3,4], minval=-1, maxval=1)
a = tf.Variable(Rand, dtype=tf.float32)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    argmax_op_0 = tf.argmax(a, axis=0)
    argmax_op_1 = tf.argmin(a, axis=1)
    
    print(sess.run(a))
    print(sess.run(argmax_op_0))
    print(sess.run(argmax_op_1))

[[ 0.5196247   0.86279774  0.5919924  -0.1379559 ]
 [-0.36952686 -0.30311322 -0.23647308 -0.9966116 ]
 [-0.7433636  -0.04305339 -0.3477869  -0.5821161 ]]
[0 0 0 0]
[3 3 0]


In [ ]:
tf.equal()
判断两个 Tensor 是否每个元素都相等，返回一个格式为 bool 的 Tensor

In [ ]:
tf.cast()
将 x 的数据类型转换为 dtype

In [44]:
a = tf.Variable([0,1,1,0])
b = tf.cast(a, dtype=tf.bool)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(sess.run(b))

[False  True  True False]


tf.matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)
transpose_a / True，a 会在参与运算之前，先将其转置一下
a_is_sparse / True，a 会被当做稀疏矩阵来参与运算

In [ ]:
tf.trainable_variables()
返回所有可训练的变量
在创造变量 (tf.Variable tf.get_variable) 等操作时，都会有一个 trainable 选项，表示该变量是否可训练
这个函数会返回图中所有 trainable=True 的变量
tf.Variable tf.get_variable 的默认选项为 True
tf.constant 只能是 False
? 那么，bias 为什么使用 tf.constant，难道不需要训练吗

In [51]:
with tf.variable_scope('123'):
    a = tf.get_variable('a',shape=[5,2])    # 默认 trainable=True
    b = tf.get_variable('b',shape=[2,5],trainable=False)
    c = tf.constant([1,2,3],dtype=tf.int32,shape=[8],name='c') # 因为是常量，所以trainable=False
    d = tf.Variable(tf.random_uniform(shape=[3,3]),name='d')
    tvar = tf.trainable_variables()
    tvar_name = [x.name for x in tvar]
    print(tvar)
    print(tvar_name)

ValueError: Variable 123/a already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Matrix\Jupyter\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()
  File "C:\Matrix\Jupyter\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "C:\Matrix\Jupyter\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)


In [ ]:
tf.gradients()
用来计算导数

In [ ]:
tf.clip_by_global_norm
修正梯度值，用于 '控制梯度爆炸' 的问题
梯度爆炸和梯度消失的原因都是一样的，因为链式求导的关系，导致梯度的指数级衰减

tf.clip_by_average_norm
tf.clip_by_norm
tf.clip_by_value

# 都是同样作用吗？

In [ ]:
tf.nn.dropout()
按概率来将 x 中的一些元素置零，并将其他值放大
用于进行 dropout 操作，一定程度上可以防止过拟合
没有清零的元素，则会统一乘以 1/keep_prob，目的是为了保持 x 的整体期望值不变

In [52]:
sess = tf.InteractiveSession()
a = tf.get_variable('a',shape=[2,5])
b = a
a_drop = tf.nn.dropout(a,0.8)
sess.run(tf.initialize_all_variables())
print(sess.run(b))
print(sess.run(a_drop))

C:\Matrix\Jupyter\lib\site-packages\tensorflow\python\client\session.py:1662: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


ValueError: Variable a already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "C:\Matrix\Jupyter\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()
  File "C:\Matrix\Jupyter\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "C:\Matrix\Jupyter\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)


In [ ]:
tf.assign(ref, value, validate_shape=None, use_locking=None, name=None)
用来更新模型中变量的值
ref是待赋值的变量
value是要更新的值
ref = value

In [54]:
sess = tf.InteractiveSession()
 
a = tf.Variable(0.0)
b = tf.placeholder(dtype=tf.float32,shape=[])
op = tf.assign(a,b)
 
sess.run(tf.initialize_all_variables())
print(sess.run(a))
# 0.0
sess.run(op,feed_dict={b:5.})
print(sess.run(a))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
0.0
5.0


In [ ]:
tf.name_scope()
tf.variable_scope()

tf.get_variable_scope()
返回当前变量的命名域