# Magical Command

**`运行 python 文件 : %run`**

In [1]:
%run mine_model/model01/func01.py

Here is my func 10
Here is my func 20
Here is my func 30


**`导入自定义模块`**

In [2]:
import mine_model.model01.func01 as func

__init__
Here is my func 10
Here is my func 20
Here is my func 30


In [3]:
func.say()

Here is my func 1


In [4]:
from mine_model.model01 import func01

In [5]:
func01.say()

Here is my func 1


**`测试代码运行时间`**

**`%timeit`**
+ 后面只能加一个语句

In [6]:
%timeit L = [ i**2 for i in range(1000) ]

203 µs ± 1.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


**`%%timeit`**
+ 测试一段程序

In [7]:
%%timeit
L = []
for n in range(1000):
    L.append(n ** 2)

250 µs ± 2.82 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


+ **`timeit : 系统会自动执行 x 次`**
+ **`time : 系统只会执行一次，结果不稳定`**

In [8]:
%time L = [ i**2 for i in range(1000) ]

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 226 µs


In [9]:
%%time
L = []
for n in range(1000):
    L.append(n ** 2)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 325 µs


# Numpy About

In [10]:
import numpy as np

**`np.full()`**

In [11]:
np.full((3,5), fill_value=1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.full((3,5), fill_value=1.0001)

array([[1.0001, 1.0001, 1.0001, 1.0001, 1.0001],
       [1.0001, 1.0001, 1.0001, 1.0001, 1.0001],
       [1.0001, 1.0001, 1.0001, 1.0001, 1.0001]])

**`np.arange()`**
+ np.arange(start, stop, step)
+ [start, stop) 步长为 step

+ python range 不可以传入'浮点数'
    + [Wrong] : range(0, 1, 0.2)

In [13]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(10, step=2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**`np.linspce()`**
+ np.linspace(start, stop, num=50)
+ [start, stop] 等长去 num 个点

In [17]:
np.linspace(0, 8, 5)

array([0., 2., 4., 6., 8.])

**`np.random`**

+ **`np.random.seed()`** : 固定随机种子

+ **`np.random.randint(low, high, size)`** : [low, high)

In [18]:
np.random.seed(1314)
np.random.randint(4, 8, size=(3,4))

array([[5, 5, 7, 7],
       [4, 7, 4, 5],
       [6, 4, 7, 4]])

In [19]:
np.random.seed(1314)
np.random.randint(4, 8, size=(3,4))

array([[5, 5, 7, 7],
       [4, 7, 4, 5],
       [6, 4, 7, 4]])

**`切片 & 选取`**

+ X[a:b:c] : c - 步长
+ **`多层索引 or 切片`**
    + X[2][2] / X[:2][:2] : 不建议
    + X[2,2] / X[:2, 2] : Recomand

+ numpy 中修改`子矩阵`，`原矩阵`也会跟着修改，`反之相同`
+ **`np.copy()`** : 对拷贝矩阵修改，不会影响`原矩阵`

In [20]:
Arr = np.arange(12).reshape(3,4)
Arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
Arr = np.arange(12).reshape(3,4)
sub = Arr[:2, :2]
sub[0,0] = 100
print(">> Arr\n", Arr)
print("\n>> sub\n", sub)

>> Arr
 [[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]

>> sub
 [[100   1]
 [  4   5]]


In [22]:
Arr = np.arange(12).reshape(3,4)
sub = Arr[:2, :2]
Arr[0,0] = 100
print(">> Arr\n", Arr)
print("\n>> sub\n", sub)

>> Arr
 [[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]

>> sub
 [[100   1]
 [  4   5]]


In [23]:
Arr = np.arange(12).reshape(3,4)
sub = Arr[:2,:2].copy()
sub[0,0] = 100
print(">> Arr\n", Arr)
print("\n>> sub\n", sub)

>> Arr
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

>> sub
 [[100   1]
 [  4   5]]


**`合并`**
+ np.concatenate()
+ np.vstack() / np.r_[]
+ np.hstack() / np.c_[]

In [24]:
a = np.arange(0,4).reshape(1,-1)
b = np.arange(5,9).reshape(1,-1)

+ **`axis`**
    + 一般默认 : axis=0
    + axis=0 : 第一个维度，row
    + axis=1 : 第儿个维度，col

**`np.concatenate()`**
+ axis=0 : 沿着`第一个维度`连接，即：沿着行连接，增加行维度
+ axis=1 : 沿着`第二个维度`连接，即：沿着列连接，增加列维度

In [25]:
np.concatenate([a, b])

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [26]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 5, 6, 7, 8]])

In [27]:
np.hstack([a,b])

array([[0, 1, 2, 3, 5, 6, 7, 8]])

In [28]:
np.c_[a,b]

array([[0, 1, 2, 3, 5, 6, 7, 8]])

In [29]:
np.vstack([a,b])

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [30]:
np.r_[a,b]

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

**`分割`**
+ np.split()
+ np.vsplit()
+ np.hsplit()

**`np.split(ary, indices_or_sections)`** : 分割点，n-dim对应第一维度

In [31]:
ary = np.arange(10)
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.split(ary, [2,5,8])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7]), array([8, 9])]

In [33]:
np.split()

TypeError: split() missing 2 required positional arguments: 'ary' and 'indices_or_sections'

In [34]:
arr = np.arange(32).reshape(8,-1)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [35]:
np.split(arr, [2,5,6])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]), array([[20, 21, 22, 23]]), array([[24, 25, 26, 27],
        [28, 29, 30, 31]])]

In [36]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [37]:
np.vsplit(arr, [2,5,6])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]), array([[20, 21, 22, 23]]), array([[24, 25, 26, 27],
        [28, 29, 30, 31]])]

In [38]:
np.hsplit(ary, [2,5,8])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7]), array([8, 9])]

**`广播 / 向量&矩阵运算`**

In [39]:
var = 1
row = np.array([-1, -2, -3, -4])
matrix = np.arange(12).reshape(-1,4)

In [40]:
matrix + var

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
matrix + row

array([[-1, -1, -1, -1],
       [ 3,  3,  3,  3],
       [ 7,  7,  7,  7]])

In [42]:
matrix * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
matrix ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

**`linear`**

**`np.linalg.inv() / pinv()`**
+ 逆：要求`方阵`
+ 伪逆：不要求形状

In [44]:
arr = np.array([[1,5],[9,19]])

In [45]:
invArr = np.linalg.inv(arr)

In [46]:
invArr @ arr

array([[ 1.00000000e+00, -4.44089210e-16],
       [ 5.55111512e-17,  1.00000000e+00]])

In [47]:
arr @ invArr

array([[1., 0.],
       [0., 1.]])

In [48]:
arr = np.arange(0, 9).reshape(3,3)

In [49]:
invArr = np.linalg.pinv(arr)

In [50]:
arr @ invArr

array([[ 0.83333333,  0.33333333, -0.16666667],
       [ 0.33333333,  0.33333333,  0.33333333],
       [-0.16666667,  0.33333333,  0.83333333]])

**`聚合操作`**
+ np.sum()
+ np.max() / min()
+ np.mean() / median() / var() / std()

In [51]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
np.sum(arr)

66

In [53]:
np.sum(arr, axis=0)

array([12, 15, 18, 21])

In [54]:
np.sum(arr, axis=1)

array([ 6, 22, 38])

+ **`axis = 0`**
    + 沿着行的方向 == 把'row'轴压缩

In [55]:
np.mean(arr)

5.5

In [56]:
np.mean(arr, axis=0)

array([4., 5., 6., 7.])

In [57]:
np.mean(arr, axis=1)

array([1.5, 5.5, 9.5])

**`index aboud`**
+ np.argmax() / argmin() / argsort()

In [58]:
arr = np.random.randint(10, size=(3,4))
arr

array([[7, 0, 9, 7],
       [6, 2, 3, 2],
       [6, 3, 7, 1]])

In [59]:
np.argmax(arr, axis=0)

array([0, 2, 0, 0])

In [60]:
np.argmin(arr, axis=1)

array([1, 1, 3])

In [61]:
np.argsort(arr)

array([[1, 0, 3, 2],
       [1, 3, 2, 0],
       [3, 1, 0, 2]])

In [62]:
np.argsort(arr, axis=0)

array([[1, 0, 1, 2],
       [2, 1, 2, 1],
       [0, 2, 0, 0]])

**`np.any() / np.all()`**

In [63]:
X = np.array([0,1,2,3,4])

In [64]:
np.any(X)

True

In [65]:
np.all(X)

False

`&`

In [66]:
(X>1) & (X<6)

array([False, False,  True,  True,  True])

In [67]:
X[(X>1) & (X<6)]

array([2, 3, 4])

**``**

**``**

**``**

**``**