In [1]:
import tensorflow as tf
import numpy as np

# Tensor

+ 张量可以被简单理解为多维数组
+ 在张量中并没有真正保存数字，它保存的是如何得到这些数字的计算过程

In [2]:
a = tf.constant([[1,2,3],[1,2,3],[1,2,3],[1,2,3]], name='a')
b = tf.constant([[3,4,5],[3,4,5],[3,4,5],[3,4,5]], name='b')

result = tf.add(a,b, name='add')
print(result)

Tensor("add:0", shape=(4, 3), dtype=int32)


In [3]:
result.get_shape()

TensorShape([Dimension(4), Dimension(3)])

+ 一个张量中主要保存了三个属性
    + 名字，name
    + 纬度，shape
    + 类型，type

**`Tensor("add:0", shape=(4, 3), dtype=int32)`**
+ 张量的第一个属性名字不仅是一个张量的唯一标识符，它同样给出了这个张量是如何计算出来的
+ 张量和计算图上节点所代表的计算结果是对应的
    + "node : src_output" 的形式
    + src_output 表示当前张量来自节点的第几个输出

    + type：每个张量都会有唯一类型
    + 如果不指定类型，Tensorflow 会给出默认的类型
        +比如不带小数点的数会被默认为 int32，带小数点的会默认为 float32

+ **`张量的作用`**
    + 对中间计算结果的引用，提高代码的可读性
    + 通过张量来存储中间结果，方便获取中间结果
    + **`Tensor.get_shape()`** 可以快速获取张量的纬度信息

**`Tensor & Variable`**
+ Tensorflow 的核心概念是 Tensor，所有的数据都是通过 Tensor 的形式来组织的
+ Variable 的声明函数 tf.Variable() 只是一个运算
+ 这个运算的输出结果就是一个张量
+ **`变量只是一种特殊的张量`**

-----------------

# Constant & Variable

**`tf.constant`**(value, dtype=None, shape=None, name='Const', verify_shape=False)
+ tf.constant_initializer

In [4]:
cost = tf.constant([1,2,3,4])
with tf.Session() as sess:
    print(sess.run(cost))

[1 2 3 4]


In [5]:
bias = tf.constant(0.0, dtype=tf.float32, shape=[1,8])
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(sess.run(bias))

[[0. 0. 0. 0. 0. 0. 0. 0.]]


----------------------------------

**`tf.Variable`**(initial_value, trainable, collections, validate_shape, name, dtype)
+ initial_value : A `Tensor`, or Python object convertible to a `Tensor`, which is the initial value for the Variable.
+ trainable: 
    + If `True`, the default, also adds the variable to the graph collection `GraphKeys.TRAINABLE_VARIABLES`. 
    + This collection is used as the default list of variables to use by the `Optimizer` classes.
+ collections: 
    + List of graph collections keys. 
    + The new variable is added to these collections. Defaults to `[GraphKeys.GLOBAL_VARIABLES]`.
+ validate_shape: 
    + If `False`, allows the variable to be initialized with a value of unknown shape.
    + If `True`, the default, the shape of `initial_value` must be known.

In [6]:
zeros = tf.zeros([3,4])
var = tf.Variable(zeros)
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(sess.run(var))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
weights = tf.Variable(tf.random_normal([2,3], stddev=2))

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(sess.run(weights))

[[-0.321705   -6.908461    0.25333065]
 [-2.4780028  -1.1168464   2.2765076 ]]


-------

# Variable & Placeholder & Fetch

**`Fetch`**
+ 在一个绘画中可以`同时执行多个op`

In [8]:
input1 = tf.constant(3.0)
input2 = tf.constant(2.0)
input3 = tf.constant(5.0)

add = tf.add(input2, input3)
mul = tf.multiply(input1, add)

with tf.Session() as sess:
    result = sess.run([mul, add])  # <<<　Fetch
    print("[mul, add] :", result)

[mul, add] : [21.0, 7.0]


----------------------------------

**`Feed`**
+ **在运行时, 才传入相应的值**
+ 占位符 : tf.placeholder(tf.float32)
+ feed_dict = {.. value ..}

In [9]:
input1 = tf.placeholder(tf.float32)  # 创建 float32 类型的占位符
input2 = tf.placeholder(tf.float32)

output = tf.multiply(input1, input2)

with tf.Session() as sess:
    res = sess.run(output, feed_dict={
        input1:[7.0],
        input2:[2.]
    })
    print(res)

[14.]


In [10]:
w1 = tf.Variable(tf.random_normal([3,2], stddev=1))
w2 = tf.Variable(tf.random_normal([1,3], stddev=1))

x = tf.placeholder(tf.float32, shape=(2,3), name="input")
a = tf.matmul(w1, x)
y = tf.matmul(w2, a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    res = sess.run(y, feed_dict={
        x : [[0.7,0.5,0.5],[0.9,0.4,0.8]]
    })
    print(res)

[[2.1395674 1.2711904 1.6946031]]


**`tf.placeholder() & feed_dict=`**
+ Tensorflow 提供了一个 placeholder 机制用于提供输入数据
+ placeholder 相当于定义一个位置，这个位置中的数据在程序运行时再指定


+ `tf.placeholder(tf.float32, shape=(2,3), name="input")`
    + 在 placeholder 定义时，这个位置上的数据类型是需要指定的，并不可以改变
    + placeholder 中的数据纬度信息，可以根据提供的数据推导出来，所以不一定要给出
    + 计算向前传播结果时，需要提供一个 feed_dict 来指定 x 的取值
    + feed_dict 是一个字典，在字典中需要给出每个用到的 placeholder 的取值

# get_variable & variable_scope("", reuse= )

**`tf.get_variable`**(name, shape=None, dtype=None, initializer=None, regularizer=None, trainable=None, collections=None)
+ 初始化更方便
```
W = tf.get_variable("W", shape=[784, 256], initializer=tf.contrib.layers.xavier_initializer())
```

**`tf.variable_scope`**(name_or_scope, reuse=None)

+ 当神经网络的结构更加复杂, 参数更多时, 就需要一个更好的方式来传递和管理神经网络中的参数
+ Tensorflow 提供了`通过变量名称`来创建或者获取一个变量的机制
+ 通过这个机制, 在不同的函数中可以直接通过变量的名字来使用变量, 而不需要将变量通过参数的形式到处传递

+ tf.get_variable() 用于创建变量时, 它和 tf.Variable() 的功能是基本等价的
    + 对于 tf.Variable 函数, 变量名称是一个可选的参数
    + 对于 tf.get_variable 函数, 变量名称是一个必选参数
```
    v = tf.get_variable("var_00", shape=[1], initializer=tf.constant_initializer(1.0))
    v = tf.Variable(tf.constant(1.0, shape=[1]), name='var_00')
```

----

**`tf.get_variable 工作机制`**

+ 当 `tf.get_variable_scope().reuse == False`，调用该函数会创建新的变量
```
      with tf.variable_scope("foo"):
          v = tf.get_variable("v", [1])
      assert v.name == "foo/v:0"
```
    　　

+ 当 `tf.get_variable_scope().reuse == True`，调用该函数会重用已经创建的变量
```
      with tf.variable_scope("foo"):
          v = tf.get_variable("v", [1])
      with tf.variable_scope("foo", reuse=True):
          v1 = tf.get_variable("v", [1])
      assert v1 is v
```

----

**`tf.variable_scope 工作机制`**

+ `tf.variable_scope()`用来指定变量的作用域，作为变量名的前缀，支持嵌套
```
    with tf.variable_scope("foo"):
        with tf.variable_scope("bar"):
            v = tf.get_variable("v", [1])
    assert v.name == "foo/bar/v:0"
```

+ 当前环境的作用域可以通过函数 `tf.get_variable_scope()` 获取
+ 并且 **`reuse flag`** 可以通过调用 `reuse_variables()` 设置为True
```
    with tf.variable_scope("foo"):
        v = tf.get_variable("v", [1])
        tf.get_variable_scope().reuse_variables()
        v1 = tf.get_variable("v", [1])
    assert v1 is v
```

----

**`Sharing variables`**
+ 使用`tf.variable_scope()`来生成一个上下文管理器, 在这个上下文管理器中, 通过`tf.get_variable()`来`创建/获取`变量
+ **`tf.variable_scope(., reuse=True)`** & **`tf.get_variable()`** 获取
    + 获取 : 如果变量不存在, 则tf.get_variable()将报错
    + 创建 : 如果同名的变量已经存在, 则tf.get_variable()函数将报错

**`reuse = tf.AUTO_REUSE`**
+ 自动复用
+ 如果变量存在则复用，不存在则创建
+ 避免了代码的繁琐

In [11]:
def foo():
    with tf.variable_scope("foo", reuse=tf.AUTO_REUSE):
        v = tf.get_variable("v", [1], initializer=tf.ones_initializer)
    return v

v1 = foo()  # Creates v.
v2 = foo()  # Gets the same, existing v.

print(v1.name)
print(v2.name)
assert v1 == v2

foo/v:0
foo/v:0


**`Example - 00`**

In [12]:
with tf.Session() as sess:
    with tf.variable_scope("Tyrion"):
        var = tf.get_variable('var_01', [1], initializer=tf.zeros_initializer)
        print(var.name)

    with tf.variable_scope("Tyrion", reuse=True):
        get_var = tf.get_variable("var_01")
        tf.global_variables_initializer().run()
        print(sess.run(get_var))

Tyrion/var_01:0
[0.]


**`Example - 01`**

In [13]:
with tf.variable_scope("foo"):
    with tf.variable_scope("bar"):
        v = tf.get_variable("var_02", [1])
        assert v.name == "foo/bar/var_02:0"

**`Example - 02`**

In [14]:
def conv_relu(input, kernel_shape, bias_shape):
    weights = tf.get_variable("weights", kernel_shape, initializer=tf.random_normal_initializer())
    biases = tf.get_variable("biases", bias_shape, initializer=tf.constant_initializer(0.0))
    conv = tf.nn.conv2d(input, weights, strides=[1, 1, 1, 1], padding='SAME')
    return tf.nn.relu(conv + biases)

In [15]:
# 需要两个卷积层，可以通过 tf.variable_scope() 指定作用域进行区分
# 如 with tf.variable_scope("conv1") 指定了第一个卷积层作用域为conv1
# 在这个作用域下有两个变量 weights 和 biases

def my_image_filter(input_images):
    with tf.variable_scope("conv1"):
        # Variables created here will be named "conv1/weights", "conv1/biases".
        relu1 = conv_relu(input_images, [5, 5, 32, 32], [32])
    with tf.variable_scope("conv2"):
        # Variables created here will be named "conv2/weights", "conv2/biases".
        return conv_relu(relu1, [5, 5, 32, 32], [32])

+ 在 image_filters 这个作用域, 重复使用第一张图片输入时创建的变量，调用函数reuse_variables()
```
with tf.variable_scope("image_filters") as scope:
    result1 = my_image_filter(image1)
    scope.reuse_variables()
    result2 = my_image_filter(image2)
```

**`Example - 03`**

In [16]:
def func(in_put, in_channel, out_channel):
    with tf.variable_scope(name_or_scope='', reuse=tf.AUTO_REUSE): ### 改动部分 ###
        weights = tf.get_variable(name="weights", shape=[2, 2, in_channel, out_channel], 
                                  initializer=tf.contrib.layers.xavier_initializer_conv2d())
        convolution = tf.nn.conv2d(input=in_put, filter=weights, strides=[1, 1, 1, 1], padding="SAME")
        return convolution

def main():
    with tf.Graph().as_default():
        input_x = tf.placeholder(dtype=tf.float32, shape=[1, 4, 4, 1])
        for _ in range(5):    # 重复调用
            output = func(input_x, 1, 1)
            with tf.Session() as sess:
                sess.run(tf.global_variables_initializer())
                _output = sess.run([output], feed_dict={
                    input_x : np.random.uniform(low=0, high=255, size=[1, 4, 4, 1])
                })
                # print(_output)

if __name__ == "__main__":
    main()

--------------------------------------------------------

# generator

+ **`Use already have value`**
+ **`Fix Value`**
+ **`Sequence`**
+ **`Random Value`**
+ **`initializer`**

**`Tensor.initialized_value()`**

In [17]:
weights = tf.Variable(tf.random_normal([2,3], stddev=2))

weights_ = tf.Variable(weights.initialized_value() * 2.0)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(sess.run(weights))
    print()
    print(sess.run(weights_))

[[-0.09402636  2.5565817  -1.3705839 ]
 [-0.3344355   1.6579056   1.5512991 ]]

[[-0.18805273  5.1131635  -2.7411678 ]
 [-0.668871    3.3158112   3.1025982 ]]


**`Fix Value`**
+ tf.`fill`(dims, value, name=None)
+ tf.`zeros`(shape, dtype=tf.float32, name=None) / tf.`ones`( )
+ tf.`zeros_like`(tensor, dtype=None, name=None, optimize=True) / tf.`ones_like`( )

In [18]:
f_one = tf.fill([3,4], 1)

with tf.Session() as sess:
    print(sess.run(f_one))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
ones = tf.ones([4,4])
zeros = tf.zeros([3,4])
zeros_l = tf.zeros_like(ones)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(sess.run(zeros))
    print(sess.run(zeros_l))
    print()
    print(zeros.get_shape())
    print(zeros_l.get_shape())

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

(3, 4)
(4, 4)


**`Sequence`**

+ **`tf.linspace(start, stop, num, name=None)`**
    + 在 [start,stop] 范围内产生 num 个数的等差数列
    + start & stop 要用浮点数表示
    
+ **`tf.range(start, limit=None, delta=1, dtype=None, name='range')`**
    + 在 [start,limit) 范围内以步进值 delta 产生等差数列

In [20]:
x = tf.linspace(start=1.0, stop=5.0, num=5, name=None)
y = tf.range(start=1,limit=5, delta=1)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))

[1. 2. 3. 4. 5.]
[1 2 3 4]


**`Random Value`**

+ **`tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)`**
    + Outputs random values from a normal distribution.
    + 正态分布

+ **`tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)`**
    + Outputs random values from a truncated normal distribution.
    + 截断正态分布，只保留 [mean-2*stddev, mean+2*stddev] 内的随机数

+ **`tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)`**
    + Outputs random values from a uniform distribution.
    + 均匀分布 : [minval, maxval)

**`initializer`**

+ tf.ones_initializer(dtype=tf.float32)
+ tf.zeros_initializer(dtype=tf.float32)
+ tf.constant_initializer(value=0, dtype=tf.float32, verify_shape=False)
+ tf.random_uniform_initializer(minval=0, maxval=None, seed=None, dtype=tf.float32)
+ tf.random_normal_initializer(mean=0.0, stddev=1.0, seed=None, dtype=tf.float32)
+ tf.truncated_normal_initializer(mean=0.0, stddev=1.0, seed=None, dtype=tf.float32)

---------------

# Graph & Session

+ Tensorflow 中的每一个计算都是计算图上的一个节点，而节点之间的边描述了计算之间的依赖关系


+ Tensorflow 程序中，系统会自动维护一个默认的计算图
    + **`tf.get_default_graph()`**：获取当前默认的计算图
    + **`Tensor.graph`**：查看张量所属的计算图

In [21]:
a = tf.constant(1)
a.graph is tf.get_default_graph()

True

+ **`tf.Graph()`**:生成新的计算图
    + `with tf.Graph().as_default()`
    + `with tf.Session(graph=…) as sess:`


+ **`不同计算图上的 "张量 & 运算" 都不会共享`**

In [22]:
g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable('var_03', initializer=tf.zeros(shape=[1]))

g2 = tf.Graph()
with g2.as_default():
    v = tf.get_variable('var_03', initializer=tf.ones(shape=[1]))

with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable('var_03')), "in Graph-01")

with tf.Session(graph=g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable('var_03')), "in Graph-02")

[0.] in Graph-01
[1.] in Graph-02


----------

**`Session / 会话`**

+ `会话拥有并管理 Tensorflow 程序运行时的所有资源`


+ 当所有计算完成之后，需要关闭会话来帮助系统回收资源，否则就可能出现资源泄露的问题
    + Method.01 : 明确调用会话生成和关闭函数
    + Method.02 : 为了解决异常退出时，资源释放的问题
        + Tensorflow 可以通过 Python 的上下文管理器来使用会话
        + 当上下文管理器退出时，则会自动释放所有资源

+ tensorflow中的Tensor是保存了计算这个值的路径(方法)，当我们run的时候，tensorflow后端就通过路径计算出Tensor对应的值

`Method-01`

In [23]:
sess = tf.Session()
# sess.run(...)
sess.close()

`Method-02`

In [24]:
with tf.Session() as sess:
    pass

+ 与 graph 不同的是, **`Tensorflow 不会自动生成默认的会话，而是需要手动指定`**
    + `sess.as_default`

In [25]:
test = tf.constant([1,2,3], name='test')

sess = tf.Session()
with sess.as_default():
    print(sess is tf.get_default_session())
    
    print(test.eval() == sess.run(test))
    print(test.eval())
    print(sess.run(test))

True
[ True  True  True]
[1 2 3]
[1 2 3]


**`Tensor.eval() & tf.get_default_session().run(Tensor)`**
+ **`sess.run() 可以一步获取多个tensor中的值`**

In [26]:
a = tf.constant([1, 2, 3], name='a')
b = tf.constant([3, 4, 5], name='b')

add = tf.add(a, b, name='add')
mul = tf.multiply(a, b, name='mul')

with tf.Session() as sess:
    print(sess.run([add, mul]))
    print(add.eval(session=sess), mul.eval(session=sess))

[array([4, 6, 8]), array([ 3,  8, 15])]
[4 6 8] [ 3  8 15]


-------

# tf.collection / 集合 / 整合资源

+ 在一个计算图中，可以通过集合 collection 来管理不同类别的资源
    + 资源类型：张量、变量
+ collection 提供了一种 '零存整取' 的思路：
    + 在任意位置，任意层次都可以创建对象，存入相应的 collection 中
    + 创建完成后，统一从一个 collection 中取出一类变量，施加相应的操作
    + collection 提供一个全局的存储机制，不会受到变量名生存空间的影响
    
+ 通过 `tf.add_to_collection()` 可以将资源加入一个或多个集合中
+ 然后通过 `tf.get_collection()` 获取一个集合里面的所有资源

**`tf.GraphKeys`**

+ tf.GraphKeys.**GLOBAL_VARIABLES**
    + 默认的 Variable 对象集合，在分布式环境共性
    + 使用场景：持久化 Tensorflow 模型


+ tf.GraphKeys.**LOCAL_VARIABLES**
    + 每台计算机的局部变量
    + 通常用于临时变量，如：计数器
    + 使用 tf.contrib.framework.local_variable 添加到此集合


+ tf.GraphKeys.**MODEL_VARIABLES**
    + 在构建模型时，所有用于正向传播的 Variable 都将添加到这里
    + 使用 tf.contrib.framework.model_variable 添加到此集合


+ tf.GraphKeys.**TRAINABLE_VARIABLES**
    + 将有优化器训练的变量
    + tf.trainable_variables()


+ tf.GraphKeys.**SUMMARIES**
    + 日志生成相关的张量
    + Tensorflow 计算可视化


+ tf.GraphKeys.**MOVING_AVERAGE_VARIABLES**
    + 所有计算了滑动平均值的变量
    + tf.moving_average_variables


+ tf.GraphKeys.**REGULARIZATION_LOSSES**
    + 收集在图构造期间正则化损失

----

**`tf.add_to_collection(name, value)`**
+ name: The key for the collection. The GraphKeys class contains many standard names for collections.
+ value: The value to add to the collection.


**`tf.get_collection(key, scope=None)`**
+ key: The key for the collection. For example, the GraphKeys class contains many standard names for collections.
+ return:
    + `The list of values` in the collection with the given `name`, or an empty list if no value has been added to that collection.
    + The list contains the values in the order under which they were collected.

`tf.get_collection() 按照添加时的'顺序 & 结构'获取'集合元素'`

In [27]:
a = tf.constant([1,2], name='a')
b = tf.constant([3], name='b')
tf.add_to_collection('Test', a)
tf.add_to_collection('Test', b)
tf.add_to_collection('Test', [a,b])

vars = tf.get_collection('Test')
for var in vars:
    print(var)
print('---------')

with tf.Session() as sess:
    for var in vars:
        if not isinstance(var, list):
            print(var.name, sess.run(var))

Tensor("a_2:0", shape=(2,), dtype=int32)
Tensor("b_2:0", shape=(1,), dtype=int32)
[<tf.Tensor 'a_2:0' shape=(2,) dtype=int32>, <tf.Tensor 'b_2:0' shape=(1,) dtype=int32>]
---------
a_2:0 [1 2]
b_2:0 [3]


----

`tf.get_variable & tf.get_colletion`
+ tf.get_variable() 中 `collections=None` 等价于 `collection=[tf.GraphKeys.GLOBAL_VARIABLES]`

In [28]:
a = tf.get_variable("a_01", [3,2], initializer=tf.random_normal_initializer())
b = tf.get_variable("a_02", [10], initializer=tf.random_normal_initializer())

gloable_variables = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    for var in gloable_variables:
        print(var.name, '\n', sess.run(var))

Variable:0 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Variable_1:0 
 [[ 0.9180692  -3.3838112   2.71286   ]
 [ 0.55919445 -1.089166    2.980913  ]]
Variable_2:0 
 [[0.00853385 1.6481047 ]
 [1.0352571  0.94730854]
 [0.6027661  0.51231086]]
Variable_3:0 
 [[-1.1362771 -0.8955608 -0.6792621]]
foo/v:0 
 [1.]
Tyrion/var_01:0 
 [0.]
foo/bar/var_02:0 
 [-1.3179361]
Variable_4:0 
 [[-1.7656925   0.20996203 -1.1696948 ]
 [ 0.2881413   0.06542689 -5.168431  ]]
Variable_5:0 
 [[ -3.531385     0.41992405  -2.3393896 ]
 [  0.5762826    0.13085377 -10.336862  ]]
a_01:0 
 [[ 1.093994    0.953705  ]
 [ 1.4361348  -1.1914153 ]
 [-0.57483804  1.1861914 ]]
a_02:0 
 [ 0.47713545 -0.03824668 -1.4490979   0.50916195 -0.85737807 -0.54701686
  0.42262328 -1.032796    1.7862451   1.9440341 ]


In [29]:
a = tf.get_variable(name="b_01", shape=[10], initializer=tf.zeros_initializer)
b = tf.get_variable(name="b_02", shape=[3,4], initializer=tf.ones_initializer())
tf.add_to_collection('Tyrion', a)
tf.add_to_collection('Tyrion', b)

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    keys = tf.get_collection("Tyrion")
    for key in keys:
        print(key.name, '\n', sess.run(key))    

b_01:0 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
b_02:0 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


----

+ `如果使用 get_variable 的 collections 参数，在变量声明时，就将其加入到 collection 中`
+ `获取其值时，需要通过 feed_dict`

In [30]:
a = tf.get_variable(name="c_01", shape=[1], collections=['C'])
b = tf.get_variable(name="c_02", shape=[1], collections=['C'])

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    keys = tf.get_collection("C")
    for key in keys:
        print(key.name, '\t', sess.run(key, feed_dict={key : [1]}))

c_01:0 	 [1.]
c_02:0 	 [1.]


----

**`tf.add_n(inputs, name=None)`**

Adds all input tensors element-wise.
+ inputs: A list of `Tensor` or `IndexedSlices` objects, each with same shape and type.
+ name: A name for the operation (optional).
+ Returns:
    + A `Tensor` of same shape and type as the elements of `inputs`.

In [31]:
v1 = tf.get_variable(name='d_1', shape=[1], initializer=tf.constant_initializer(0))
v2 = tf.get_variable(name='d_2', shape=[1], initializer=tf.constant_initializer(2))

tf.add_to_collection('D', v1)
tf.add_to_collection('D', v2)
 
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    print(tf.get_collection('D'))
    print(sess.run(tf.add_n(tf.get_collection('D'))))

[<tf.Variable 'd_1:0' shape=(1,) dtype=float32_ref>, <tf.Variable 'd_2:0' shape=(1,) dtype=float32_ref>]
[2.]


**`colletion & regularization`**
+ `正则化`并不前向传播，只是在计算损失的时候使用

`add to colletion`
```python
l2_reg = tf.contrib.layers.l2_regularizer(scale=0.001)

w = tf.get_variable('weight_1', [10, 20], dtype=tf.float32,
                    initializer=tf.contrib.layers.xavier_initializer())
tf.add_to_collection('regularizer_1', l2_reg(w))
conv = tf.nn.conv2d(input, w, [1,stride,stride,1], padding='SAME')

# bias 使用 tf.constant 来定义，难道不用优化吗？
b = tf.get_variable('bias', [out_dim], dtype=tf.float32,
                    initializer=tf.constant_initializer(0.))
tf.add_to_collection('regularizer_1', l2_reg(b))

out = tf.nn.bias_add(conv, b)
```

`calc loss`
```python
regular = tf.add_n(tf.get_collection('regularizer_1'), 'loss')

with tf.variable_scope(name='loss') as scope:
    loss = -tf.reduce_sum(label * tf.log(predict)) + regular
    # cross entropy + l2_reg
```

----

`tf.get_variable() & tf.variable_scope()`

+ `tf.get_variable() & tf.variable_scope()` 这两个都有 `regularizer` 形参
+ 如果传入这个参数的话，那么 variable_scope 中的 weights 的正则化损失就会被添加到 `GraphKeys.REGULARIZATION_LOSSES` 中

In [32]:
regular = tf.contrib.layers.l1_regularizer(0.1)

with tf.variable_scope('var_1',
                       initializer=tf.random_normal_initializer(),
                       regularizer=regular):
    weight_1 = tf.get_variable('weight_01', shape=[8], initializer=tf.ones_initializer())

with tf.variable_scope('var_2',
                       initializer=tf.random_normal_initializer(),
                       regularizer=regular):
    weight_2 = tf.get_variable("weight_02", shape=[8], initializer=tf.ones_initializer())

regularization_loss = tf.reduce_sum(tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES))

----

`tf.contrib.layers.l2_regularizer()`

In [33]:
Tyrion = tf.Graph()
with Tyrion.as_default():
    weight_decay = 0.1
    init = tf.constant([0,1,2,3],dtype=tf.float32)

    """
    l2_reg = tf.contrib.layers.l2_regularizer(weight_decay)
    a = tf.get_variable("a_001",regularizer=l2_reg, initializer=init) 
    """
    # **上面代码的等价代码
    a  = tf.get_variable("a_001",initializer=init)
    a2 = tf.reduce_sum(a * a) * weight_decay / 2
    a3 = tf.get_variable(a.name.split(":")[0]+"/Regularizer/l2_regularizer", initializer=a2)
    tf.add_to_collection(tf.GraphKeys.REGULARIZATION_LOSSES, a2)
    # **

with tf.Session(graph=Tyrion) as sess:
    tf.global_variables_initializer().run()
    keys = tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES)
    for key in keys:
        print("%s : %s" %(key.name,sess.run(key)))

truediv:0 : 0.7


In [34]:
Jean = tf.Graph()
with Jean.as_default():
    weight_decay = 0.1
    init = tf.constant([0,1,2,3],dtype=tf.float32)

    l2_reg = tf.contrib.layers.l2_regularizer(weight_decay)
    tmp=tf.constant([0,1,2,3],dtype=tf.float32)
    a = tf.get_variable("b_001", regularizer=l2_reg, initializer=init)
    
with tf.Session(graph=Jean) as sess:
    tf.global_variables_initializer().run()
    
    print("Global Set:")
    keys = tf.get_collection("variables")
    for key in keys:
        print(key.name)
    print("--------------------")  
    
    print("Regular Set:")
    keys = tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES)
    for key in keys:
        print(key.name)
    print("--------------------")
    
    print(sess.run(a))
    reg_set = tf.get_collection(tf.GraphKeys.REGULARIZATION_LOSSES)
    l2_loss = tf.add_n(reg_set)
    print("l2_loss=%s" %(sess.run(l2_loss)))

Global Set:
b_001:0
--------------------
Regular Set:
b_001/Regularizer/l2_regularizer:0
--------------------
[0. 1. 2. 3.]
l2_loss=0.7


----

# operation / op

**`Property`**
+ `Tensor.get_shape()`
+ `tf.shape(tensor)` || sess.run()
+ `tf.reshape(tensor, shape, name=None)`

In [35]:
tensor = tf.Variable(tf.ones([3,4], dtype=tf.float32))
print(tensor.get_shape())

(3, 4)


`tf.shape() 函数本身也是返回一个张量，因而，需要用 sess.run() 来得到具体的值`

In [36]:
tensor = tf.Variable(tf.ones([3,4], dtype=tf.float32))

with tf.Session() as sess:
    print(sess.run(tf.shape(tensor)))

[3 4]


In [37]:
tensor = tf.Variable(tf.ones([3,4], dtype=tf.float32))
temp = tf.reshape(tensor, [-1,1])
print(temp.get_shape())

(12, 1)


----

**`Basic Math Method`**

**`tf.one_hot(indices, depth, dtype=None, name=None)`**

Returns a one-hot tensor.

```python
indices = [0, 1, 2]
depth = 3
tf.one_hot(indices, depth)  # output: [3 x 3]
# [[1., 0., 0.],
#  [0., 1., 0.],
#  [0., 0., 1.]]

indices = [0, 2, -1, 1]
depth = 3
tf.one_hot(indices, depth,
           on_value=5.0, off_value=0.0,
           axis=-1)  # output: [4 x 3]
# [[5.0, 0.0, 0.0],  # one_hot(0)
#  [0.0, 0.0, 5.0],  # one_hot(2)
#  [0.0, 0.0, 0.0],  # one_hot(-1)
#  [0.0, 5.0, 0.0]]  # one_hot(1)

indices = [[0, 2], [1, -1]]
depth = 3
tf.one_hot(indices, depth,
           on_value=1.0, off_value=0.0,
           axis=-1)  # output: [2 x 2 x 3]
# [[[1.0, 0.0, 0.0],   # one_hot(0)
#   [0.0, 0.0, 1.0]],  # one_hot(2)
#  [[0.0, 1.0, 0.0],   # one_hot(1)
#   [0.0, 0.0, 0.0]]]  # one_hot(-1)
```

**`tf.assign(ref, value)`**

Update 'ref' by assigning 'value' to it.

+ ref: A mutable `Tensor`. Should be from a `Variable` node. May be uninitialized.
+ value: A `Tensor`. Must have the same type as `ref`. The value to be assigned to the variable.

+ Returns:
    + A `Tensor` that will hold the new value of 'ref' after the assignment has completed.   

In [38]:
count = tf.Variable(0, name='counter')
one = tf.constant(1)
new_value = tf.add(count, one)

update = tf.assign(count, new_value)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(count))
    for _ in range(5):
        sess.run(update)
        print(sess.run(count))

0
1
2
3
4
5


In [ ]:
tf.pow

In [ ]:
tf.square

In [ ]:
tf.multiply
tf.mul
實現兩個矩陣點乘，兩個矩陣必須要相同維度

tf.matmul
將a,b兩個矩陣相乘，如果需要事先轉置的話，可以把個別的選項調成True，如果矩陣裏面包括很多0的話，可以調用spare=True轉為更有效率的演算法

对应元素相乘 *
矩阵乘法 tf.matmul


In [ ]:
自定义损失函数
loss = tf.reduce_sum(tf.where(tf.greater(v1,v2), (v1-v2) * a, (v2-v1) * b))

v1 = tf.constant([1., 2., 3., 4.])
v2 = tf.constant([4., 3., 2., 1.])
compare = tf.greater(v1, v2)
which = tf.where(compare, v1, v2)

with tf.Session() as sess:
    print(sess.run(compare))
    print(sess.run(which))

**`Statistics Method`**

----

**`calc on some axis`**

```python
tf.reduce_max(input_tensor, axis=None, keepdims=None)
tf.reduce_min(input_tensor, axis=None, keepdims=None)
tf.reduce_sum(input_tensor, axis=None, keepdims=None)
tf.reduce_mean(input_tensor, axis=None, keepdims=None)

tf.reduce_prod(input_tensor, axis=None, keepdims=None) # 连乘
    # Computes the product of elements across dimensions of a tensor. (deprecated arguments)
tf.reduce_all(input_tensor, axis=None, keepdims=None)
    # Computes the "logical and" of elements across dimensions of a tensor. (deprecated arguments)
tf.reduce_any(input_tensor, axis=None, keepdims=None)
    # Computes the "logical or" of elements across dimensions of a tensor. (deprecated arguments)
```

+ `input_tensor`: The boolean tensor to reduce.
+ `axis`: The dimensions to reduce. If None (the default), reduces all dimensions.
+ `keepdims`: If true, retains reduced dimensions with length 1. 如果为 False，执行后则会减少一个维度

```python
x = tf.constant([[1., 1., 1.], [2., 2., 2.]])
tf.reduce_mean(x)  # 1.5
tf.reduce_mean(x, 0)  # [1.5, 1.5, 1.5]
tf.reduce_mean(x, 1)  # [1., 2.]
tf.reduce_mean(x, 1, keepdims=True)  # [[1.], [2.]] / (2, 1)
```

```python
x = tf.constant([[1, 1, 1], [1, 1, 1]])
tf.reduce_sum(x)  # 6
tf.reduce_sum(x, 0)  # [2, 2, 2]
tf.reduce_sum(x, 1)  # [3, 3]
tf.reduce_sum(x, 1, keepdims=True)  # [[3], [3]]  tf.reduce_sum(x, 1, keepdims=True).get_shape()
tf.reduce_sum(x, [0, 1])  # 6
```

```python
a = tf.constant([[1,2,3], [4,5,6]])
b = tf.reduce_prod(a) 720
b_1 = tf.reduce_prod(a, axis=0) [4, 10, 18]
b_2 = tf.reduce_prod(a, axis=1) [6, 120]
b_3 = tf.reduce_prod(a, axis=0, keep_dims=True) [[4, 10, 18]]
b_4 = tf.reduce_prod(a, axis=1, keep_dims=True) [[6],[120]]
```

----

**`clip data / 裁剪数据`**
+ `tf.clip_by_average_norm(t, clip_norm, name=None)`
+ `tf.clip_by_global_norm(t_list, clip_norm, use_norm=None, name=None)`
+ `tf.clip_by_norm(t, clip_norm, axes=None, name=None)`
+ `tf.clip_by_value(t, clip_value_min, clip_value_max, name=None)`
    + Clips tensor values to a specified min and max.

In [39]:
v = tf.constant([[1.0, 2.0, 4.0],[4.0, 5.0, 6.0]])
result = tf.clip_by_value(v, 2.5, 4.5)

with tf.Session() as sess:
    print(sess.run(v))
    print(sess.run(result))

[[1. 2. 4.]
 [4. 5. 6.]]
[[2.5 2.5 4. ]
 [4.  4.5 4.5]]


----

**`Assemble / Split data`**

**`tf.concat(values, axis, name='concat')`**
+ Concatenates tensors along one dimension.

In [40]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[7, 8, 9], [10, 11, 12]]

t3 = tf.concat([t1, t2], 0)
t4 = tf.concat([t1, t2], 1)

with tf.Session() as sess:
    print(sess.run(t3))
    print()
    print(sess.run(t4))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
tf.split