In [1]:
import tensorflow as tf

# 声明张量

## 固定张量

In [2]:
# 指定维度的零张量
zero_tsr = tf.zeros([1, 2])

In [3]:
# 指定维度的单位张量
ones_tsr = tf.ones([1, 2])

In [4]:
# 指定维度的常数填充的张量
filled_tsr = tf.fill([1, 2], 32)

In [5]:
# 用已知常数张量创建张量
constant_tsr = tf.constant([1, 2, 3])

## 相似形状的张量

In [6]:
# 新建一个与给定的 tensor 类型大小一致的 tensor
zero_similar = tf.zeros_like(constant_tsr)
one_similar  = tf.ones_like(constant_tsr)

## 序列张量

In [7]:
# TensorFlow 可以创建指定间隔的张量
# PS : start, stop 需要为浮点型
linear_tsr = tf.linspace(start=0., stop=1., num=3)

In [8]:
interger_seq_tsr = tf.range(start=6, limit=15, delta=3)

## 随机张量

In [9]:
# 生成分布的随机数
randunif_tsr = tf.random_uniform([3,8], minval=0, maxval=1)

In [10]:
# 生成正态分布的随机数
randnorm_tsr = tf.random_normal([3,8], mean=0., stddev=1.)

In [11]:
# 生成带有指定边界的正态分布的随机数
# 其正态分布的随机数位于指定均值到两个标准差之间的区间
runcnorm_tsr = tf.truncated_normal([3,8], mean=0., stddev=1.)

In [12]:
# "张量 、 数组" 的随机化
shuffled_output = tf.random_shuffle(runcnorm_tsr)

In [13]:
# 张量的随机裁剪
# cropped_output = tf.random_crop(runcnorm_tsr, 3)

# 工作原理

##### > 一旦创建好了张量， 就可以通过 tf.Variable( ) 函数封装张量来作为变量

In [14]:
my_var = tf.Variable(tf.zeros([2, 3]))

# 使用外部数据

##### > 创建张量不一定非要用 TensorFlow 内建函数
##### > 可以使用 tf.convert_to_tensor() 函数将任意numpy数组转换为Python列表， 或者将常量转换为一个张量

# 使用占位符和变量

##### > 使用 TensorFlow 计算图的关键工具是占位符和变量
##### > 务必理解两者的区别， 以及什么地方该用谁

##### > 变量 ： TensorFlow 机器学习算法的参数， TensorFlow 维护/调整 这些变量的状态来优化机器学习算法
##### > 占位符 ： TensorFlow 对象， 用于表示输入输出数据的格式， 允许传入指定类型和形状的数据， 比如， 期望的计算结果

In [15]:
# tf.Variable()创建变量， 输入一个张量， 输出一个变量
# 声明变量之后， 需要初始化变量
my_var = tf.Variable(tf.zeros([2,3]))
sess = tf.Session()
init_op = tf.global_variables_initializer()
sess.run(init_op)

In [16]:
# 占位符仅仅声明数据位置， 用于传入数据到计算图
# 占位符通过会话的 feed_dict 参数获取数据
# 在计算图中使用占位符时， 必须在其上执行至少一个操作

In [17]:
# 在TensorFlow中，初始化计算图， 声明一个占位符x，
# We initialize the graph, declare x to be a placeholder, 
# and define y as the identity operation on x, which just returns x.

In [18]:
import numpy as np
sess = tf.Session()
x = tf.placeholder(tf.float32, shape=[2,2])
y = tf.identity(x)
x_vals = np.random.rand(2,2)
sess.run(y, feed_dict={x: [x_vals]})

ValueError: Cannot feed value of shape (1, 2, 2) for Tensor 'Placeholder:0', which has shape '(2, 2)'

# 操作矩阵

## 创建矩阵

In [19]:
# diag 从一个一维数组 (列表) 来创建对角矩阵
identity_matrix = tf.diag([1.0, 1.0, 1.0])
print(sess.run(identity_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
A = tf.truncated_normal([2, 3], mean=10, stddev=3)
print(sess.run(A))

[[12.733007 15.78024  11.80631 ]
 [11.976009  5.477602  9.11611 ]]


In [21]:
B = tf.fill([2,3], 5.0)
print(sess.run(B))

[[5. 5. 5.]
 [5. 5. 5.]]


In [22]:
C = tf.random_uniform([3,2])
print(sess.run(C))

[[0.9660355  0.3790257 ]
 [0.5810956  0.44652152]
 [0.3444594  0.9308642 ]]


In [23]:
D = tf.convert_to_tensor(
    np.array([[1., 2., 3.],[-3., -7.,-1.],[0., 5., -2.]])
)
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


## 矩阵的加法、减法

In [24]:
print(sess.run(A + B))

[[17.539616 17.81348  15.015653]
 [11.430141 18.134846 15.653279]]


In [25]:
print(sess.run(A - B))

[[ 6.030383    0.6550231   4.961525  ]
 [ 6.1529446   1.5125847  -0.22345161]]


## 矩阵乘法函数 matmul( )

In [26]:
# 可以通过参数指定在矩阵乘法操作前是否进行矩阵转置
# tf.matmul() https://www.jianshu.com/p/19ea2d15eb14
print(sess.run(tf.matmul(B, identity_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


## 矩阵转置

In [27]:
print(sess.run(tf.transpose(C)))

[[0.71798325 0.9840596  0.75556123]
 [0.7042396  0.65020275 0.59987223]]


## 计算矩阵行列式

In [28]:
print(sess.run(tf.matrix_determinant(D)))

-37.99999999999999


## 矩阵的逆矩阵

In [29]:
# TensorFlow 中的矩阵求逆方法是 Cholesky 矩阵分解法，又称为平方根法
# 矩阵需要为 '对称正定矩阵' or 可进行LU分解
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


## 矩阵分解

In [30]:
print(sess.run(tf.cholesky(identity_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 矩阵的 '特征值' and '特征向量'

In [31]:
# 第一个array为特征值，第二个array为特征向量
print(sess.run(tf.self_adjoint_eig(D)))

(array([-10.65907521,  -0.22750691,   2.88658212]), array([[ 0.21749542,  0.63250104, -0.74339638],
       [ 0.84526515,  0.2587998 ,  0.46749277],
       [-0.4880805 ,  0.73004459,  0.47834331]]))


# TensorFlow 计算图的其他操作

## 张量的基本操作

In [32]:
## add()、sub()、mul()、div()
## 除了特别说明之外，所有操作都是对张量的每个元素进行操作

In [33]:
## mod() 取模
print(sess.run(tf.mod(22.0, 5.0)))

2.0


# 实现激励函数

In [34]:
## TensorFlow 的激励函数位于 '神经网络库 / nn'
## 除了使用 TensorFlow 内建激励函数外，也可以使用 TensorFlow 操作设计自定义激励函数

## Rectifier Linear / ReLU - 整流线性单元

In [35]:
# 其函数为 max(0, x)
print(sess.run(tf.nn.relu([-3., 3., 10.])))

[ 0.  3. 10.]


## ReLU6 : min(max(0,x),6)

In [36]:
# 有时为了抵消 ReLU 激励函数的线性增长部分，会在min()函数中潜入max(0,x)
print(sess.run(tf.nn.relu6([-3., 3., 10.])))

[0. 3. 6.]


## sigmod( )

In [37]:
print(sess.run(tf.nn.sigmoid([-1., 0., 1.])))

[0.26894143 0.5        0.7310586 ]


## tanh( ) 双曲正切函数

In [38]:
# 与 sigmod() 函数类似
# sigmod() - [0, 1]
# tanh() - [-1, 1]
print(sess.run(tf.nn.tanh([-1., 0., 1.])))

[-0.7615942  0.         0.7615942]


## softsign( )

In [39]:
print(sess.run(tf.nn.softsign([-1., 0., 1.])))

[-0.5  0.   0.5]


## softplus( )

In [40]:
print(sess.run(tf.nn.softplus([-1., 0., 1.])))

[0.31326166 0.6931472  1.3132616 ]


# 读取数据

## 花卉数据集

In [41]:
from sklearn import datasets
iris = datasets.load_iris()

In [42]:
print("iris.data", len(iris.data))
print("iris.target", len(iris.target))
print("iris.target[0]", iris.target[0]) # Sepal length, Sepal width, Petal length, Petal width
print("set(iris.target)", set(iris.target)) # I. setosa, I. virginica, I. versicolor

iris.data 150
iris.target 150
iris.target[0] 0
set(iris.target) {0, 1, 2}


## 出生体重数据

In [43]:
# https://github.com/skumarlabs/deep_learning/blob/acd8893ccc45709008e553ae052ca4486df414fe/reference/regression/logistic_regression.py

In [1]:
import requests
birthdata_url = 'http://faculty.washington.edu/heagerty/Courses/b513/WEB2002/datasets/lowbwt.dat'  
birth_file = requests.get(birthdata_url)  
birth_data = birth_file.text.split('\n')
birth_header = [x for x in birth_data[0].split(' ') if len(x)>=1]
birth_data = [[float(x) for x in y.split(' ') if len(x)>=1] for y in birth_data[:] if len(y)>=1]

In [2]:
print(len(birth_header))

11
['85', '0', '19', '182', '2', '0', '0', '0', '1', '0', '2523']


In [50]:
print(len(birth_data))

189


In [3]:
import requests
housing_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data'
housing_header = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV0']
housing_file = requests.get(housing_url)
housing_data = housing_file.text.split('\n')
housing_data = [[float(x) for x in y.split(' ') if len(x)>=1] for y in housing_data[:] if len(y)>=1]

In [4]:
print(len(housing_data))
print(len(housing_data[0]))

506
14
